<a href="https://colab.research.google.com/github/samintelguru/python/blob/main/ProbabilityStatistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Probabilities
Probabilty is a branch of math that deals with calculating the likelihood of an event's occurence
The probabilty of an event is a value between 0 and 1
A probabity of 0 means that the event will not occur. A probablty of 1 means that the event will certainly occur.

P(A) = no of favorable outcomes/total no of outcomes

Sample space - the set of all possible outcome of an experiment. e.g. when tossing a coin the sample space is:
S ={H, T}
S ={1, 2, 3, 4, 5, 6}

Event - a subset of the sample space. It represents one or more outcomes E.G.  in flipping a coin and getting tails:
 A ={H}

Rolling a die and getting an even number

B = {2,4,6}

Outcome - single possible result from an experiment e.g  when rolling a die, an outcome could be getting 5

Types of Events:

Independent events- two events are independent if the occurence does not directly influence/affects the occurence of the other

Rolling a die and getting 5, rolling a die and getting 1

Dependent events - two events are dependent if the occurence of one directly influences the occurence of the other

Waking up late and getting to class late

Mutually exclusive events - two events are mutually exclusive if they cannot occur at the same time

me being in class and me being in town

1. Heavy rains and hiked transportation fare - Dependent
2. staying up late and being sleepy during the day - Dependent
3. it raining and the sun shining - independent
4. Running a marathon and having sore muscles - Dependent
5. Wearing grey pants and a blue shirt - independent
6. Sneezing and opening your eyes wide - mutually exclusive
7. Sleeping and eating at the same time - Mutually exclusive
8. Being darkskin and lightskin -independent or mutually exclusive
9. Being english fluent and being spanish fluent - independent
10. Having 3 siblings and 5 siblings - independent

Probabilty rules

Addition rules - the probability of either event A or B happening is the sum of their probabilities

Multiplication rules - the prob of event A AND B happening is the product of their probabilty

Create two functions: addition_rule and multiplication_rule and use them to answer the following questions

What is the probability of the following:
1. Rainy and Sunny
2. Rainy and Windy
3. Windy and foggy and sunny
4. Cloudy or sunny or windy
5. Rainy or foggy
6. Rainy or sunny


In [ ]:
def addition_rule_2(param1, param2):
  return param1 + param2

def addition_rule_3(param1, param2, param3):
  return param1 + param2

def multiplication_rule_2(param1, param2):
  return param1 * param2

def multiplication_rule_3(param1, param2, param3):
  return param1 * param2 * param3

p_rainy = 0.3
p_cloudy = 0.2
p_windy = 0.05
p_sunny = 0.4
p_foggy = 0.05

#rainy and sunny
rainy_and_sunny = multiplication_rule_2(p_rainy, p_sunny)
print(f"The probabilty of it being rainy and sunny is {rainy_and_sunny}")

#rainy and windy
rainy_and_windy = multiplication_rule_2(p_rainy, p_windy)
print(f"The probabilty of it being rainy and windy is {rainy_and_windy}")

#windy and foggy and sunny
windy_and_foggy_and_sunny = multiplication_rule_3(p_windy, p_foggy, p_sunny)
print(f"The probabilty of it being windy and foggy and sunny is {windy_and_foggy_and_sunny}")


#cloudy or sunny or windy
cloudy_or_sunny_or_windy = addition_rule_3(p_cloudy, p_sunny, p_windy)
print(f"The probabilty of it being cloudy or sunny or windy is {cloudy_or_sunny_or_windy}")

#rainy or foggy
rainy_or_foggy = addition_rule_2(p_rainy, p_foggy)
print(f"The probabilty of it being rainy or foggy is {rainy_or_foggy}")

#rainy or sunny
rainy_or_sunny = addition_rule_2(p_rainy, p_sunny)
print(f"The probabilty of it being rainy or sunny is {rainy_or_sunny}")




The probabilty of it being rainy and sunny is 0.12
The probabilty of it being rainy and windy is 0.015
The probabilty of it being windy and foggy and sunny is 0.0010000000000000002
The probabilty of it being cloudy or sunny or windy is 0.6000000000000001
The probabilty of it being rainy or foggy is 0.35
The probabilty of it being rainy or sunny is 0.7


Coditional probability- probablity of an event occurring given that another event has occurred

P(A|B) - read as the probabilty of A given B has occurred

Bayes' Theorem - used to calculate the conditional probabilty of an event based on the occurrence of another event. The formulae is:

P(A|B) = (P(A|B) * P(A)) / P(B)

P(rainy|cloudy) = (P(cloudy|rain) * P(rain))/P(cloudy)

You have been planning picnic with your family. You're trying to decide whether to postpone due to heavy rains. the chance of rain on any day is 15%. The morning of the picnicc its cloudy. The probabilty of it being cloudy is 25% and on days when rains, its cloudy in the morning 80% of the time. Should you postpone the picnic?

In [ ]:
def bayes_theorem(p_b_a, p_a, p_b):
  return (p_b_a * p_a) / p_b
p_raining = 0.15
p_cloudy = 0.25
p_cloudy_rainy = 0.8

p_rainy_cloudy= bayes_theorem(p_cloudy_rainy, p_raining, p_cloudy)
print(f"The probabilty of it raining given that it was cloudy is {p_rainy_cloudy * 100}%")

The probabilty of it raining given that it was cloudy is 48.0%


Numerical data- assumes numerical values e.g 1,2,3,4,5
Categorical data - assumes different classes eg males, females

#Measures of Central Tendancy
Measures of Central tendancy -  single values that represent the centre of a dataset

Mean/arithmetic average - used for continous numerical data. Obtained by summing up all the values and dividing by the number of observations. Mean is quite senstive to outliers

median - used for continuos numerical data. We sort the values in ascending order then pick the middle value as the median - Odd numbered list. When we have 2 middle numbers we take the mean of the two as the median. Handles outliers well

Mode - most frequent item or element in a list or dataset. Mostly used in categorical/discrete data

In [ ]:
import statistics
ages = [30, 24, 28, 36, 22, 27]
mean_age = statistics.mean(ages)
median_age = statistics.median(ages)
#mode_age = statistics.mode(ages)
print(f"The mean age is {mean_age}")
print(f"The median age is {median_age}")
#

The mean age is 27.833333333333332
The median age is 27.5


In [ ]:
import statistics
sample_data = [2,4,6,8,10,12]
cal_median = statistics.median(sample_data)
print(cal_median)


7.0


In [ ]:
gender = ["Male", "Female", "Female", "Male", "Male"]

gender_mode = statistics.mode(gender)
print(gender_mode)


Male


Range - the difference between the maximum and minimum values in a dataset

In [ ]:
numbers = [10, 22, 15, 40, 31, 29]
range_num = max(numbers) - min(numbers)
print(range_num)

30


Variance - how far the data points are to the mean. It is the avaearge of the squared difference between each datapoint and the mean

Standard Deviation - the square root of the variance. It represents average distance of each datapoint from the mean.

In [ ]:
import numpy as np
numbers = [12, 14, 16, 18, 20]
num_var = np.var(numbers)
#num_std = np.std(numbers)
print(num_var)
#print(num_std)
#mean
num_mean = statistics.mean(numbers)
# difference, square the differences, sum then divide by either N(Population) or N-1(Sample variance)
#12 - 16 = -4 ** 2 =16
#14 - 16 = -2 ** 2 = 4
#16 - 16 = 0 ** 2 = 0
#18 - 16 =2 ** 2 = 4
#20 - 16 =4 ** 2 = 16

# 16 + 4 + 0 + 4 + 16 = 40
# Population: 40/5 = 8
# Sample:40/4 =10

8.0


Create python functions to do the following:
1. Mean - takes single parameter (list) then calculates the mean and returns the result
2. Calculates the median -  takes a single parameter(list)
- if the length of the list is odd, return the middle value
- if the length of the list is even, get the mean of the two middle values

Return Median

3. Calculate variance - take a single parameter (list)
- Calculate the mean
- Get the differences
- Square the differences
- Sum of the differences
- Sum of differences /N or N-1

In [ ]:
def mean (numbers):
  return sum(numbers) / len(numbers)

def median (numbers):
  numbers.sort()
  if len(numbers) % 2 == 1:
    return numbers[len(numbers) // 2]
  else:
    return (numbers[len(numbers) // 2 - 1] + numbers[len(numbers) // 2]) / 2

def variance (numbers):
  mean_num = mean(numbers)
  differences = [(x - mean_num) ** 2 for x in numbers]
  return sum(differences) / len(numbers)


numbers = [22, 32, 12, 5, 18]
print(mean(numbers))
print(median(numbers))
print(variance(numbers))


17.8
18
83.36


In [ ]:
import numpy as np

numbers = [22, 32, 12, 5, 18]

print(np.mean(numbers))
print(np.median(numbers))
print(np.var(numbers))


17.8
18.0
83.36


3. Calculate variance - take a single parameter (list)
- Calculate the mean
- Get the differences
- Square the differences
- Sum of the differences
- Sum of differences /N or N-1

In [ ]:
def var_std_dev(numbers):
  sum_numbers = sum(numbers)
  len_numbers = len(numbers)
  mean = sum_numbers / len_numbers
  sum_sq_diff = 0
  for number in numbers:
    diff = number - mean
    square_diff = diff ** 2
    sum_sq_diff += square_diff
  var = sum_sq_diff / len_numbers
  std_dev = var ** 0.5
  return var , std_dev


numbers = [22, 32, 12, 5, 18]
variance, std_deviation = var_std_dev(numbers)

print(f"The variance is {variance}")
print(f"The standard deviation is {std_deviation}")


The variance is 83.36
The standard deviation is 9.130169768410662


# Percentiles and Quartiles

Percentiles - indicate a value below which a certain percentage of the observations or data points fall eg. the 25th percentile represents a value below which 25% of the data lies and above which 75% of the data lies.

Quartiles - divides data into four equal types

- First Quartile/ Q1 - 25% of the data falls below this value
- Second Quartile/ Q2 / Median - 50%/half of the data falls below this value
- Third Quarrtile/ Q3 / 75th percentile - value below which 75% of the data lies
-


In [ ]:
import numpy as np

sample_numbs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
q1 = np.percentile(sample_numbs, 25)
q2 = np.percentile(sample_numbs, 50)
q3 = np.percentile(sample_numbs, 75)
print(q1)
print(q2)
print(q3)


3.25
5.5
7.75


# Outliers
Outliers are extremely low values or extremely high values in a dataset

Visualized using a box and whisker plot

InterQuartileRange - IQR = Q3 - Q1

Upper bound - UB = Q3 + (1.5 * IQR)

Lower bound - LB = Q1 - (1.5 * IQR)

Anything that falls above the upper bound or below the lower bound is regarded as an outlier.

 Create a function that takes in a list as a parameter. It shoud check whether the list has outliers. If so should return a list of outliers then attempt to replace them with the median. Return with the resultant list.

In [ ]:
import numpy as np

def check_outliers(samp_numbers):
  q1 = np.percentile(samp_numbers, 25)
  q3 = np.percentile(samp_numbers, 75)
  print(f"Q1 is {q1}, Q3 is {q3}")

  iqr = q3 - q1
  upper_bound = q3 + (1.5 * iqr)
  lower_bound = q1 - (1.5 * iqr)
  median_val = np.median(samp_numbers)

  outliers = []
  for i in range(len(samp_numbers)):
    if samp_numbers[i] > upper_bound or samp_numbers[i] < lower_bound:
      outliers.append(samp_numbers[i])
      samp_numbers[i] = float(median_val)         # Here I replace outlier with median

  if outliers:
    print(f"Outliers found: {outliers}")
  else:
    print("No outliers found.")

  return samp_numbers

samp_numbers = [23, 62, 53000, 74, 15, 76, 87, -50000, 19, 10]
updated_numbers = check_outliers(samp_numbers)
print("List after replacing outliers:", updated_numbers)

Q1 is 16.0, Q3 is 75.5
Outliers found: [53000, -50000]
List after replacing outliers: [23, 62, 42.5, 74, 15, 76, 87, 42.5, 19, 10]


method 2

In [ ]:
import numpy as np

def outlier_detections(numbers):
  q1 = np.percentile(numbers, 25)
  q3 = np.percentile(numbers, 75)

  iqr = q3 - q1

  upper_bound = q3 + (1.5 * iqr)
  lower_bound = q1 - (1.5 * iqr)
  median_val = np.median(numbers)
  outliers = []

  print(f"Upper bound is {upper_bound}")
  print(f"Lower bound is {lower_bound}")
  print(f"Median is {median_val}")

  for index, number in enumerate(numbers):
    if number  > upper_bound or number < lower_bound:
      outliers.append(number)
      numbers[index] = int(median_val)
  print(f"Outliers are {outliers}")
  return (numbers)

numbers = [-20, 2, 4, 5, 8, 9, 30]

outlier_detections(numbers)

Upper bound is 16.75
Lower bound is -5.25
Median is 5.0
Outliers are [-20, 30]


[5, 2, 4, 5, 8, 9, 5]

# Probability distribution
This is a function that defines how the probabilities of different outcomes are distributed.

- Uniform distribution - every outcome in a certain range is equally likely. eg. Rolling a dice, picking a card from a deck
- Binomial distribution - describes the number of successes in a fixed number of trials, where each trial has TWO possible outcomes eg. Success or failure, True or False, Yes or No
-Poisson distribution - describes the probability of a given number of events happening in a fixed time interval, assuming that they happen at a constant rate. eg. No of people entering a lift in 10 mins
- Normal distribution - bell curve. desribes how data is clustered around the mean. As we move away from the mean it gets dispersed eg. age of students

# Hypothesis Testing
It is a statistical method that helps us make decisions or inferences about population parameters based on sample data.

- A hypothesis is a statement, opinion, remark or a thought that has not yet been proven eg. The average age of students in eMobilis is 19
eg. The best team in England is Chelsea.

- Null hypothesis - is a statement that has no effect or difference.
eg. Kibaki was the third president of Kenya - True

- Alternative hypothesis - contradicts the null hypothesis
eg. Kibaki was not the third president of Kenya. - False



Type I Error (False Positive) - this occurs when you reject the null hypothesis when it was actually true
 - Null hypothesis - steroids are bad for athletes' health. - False

 - Alternative hypothesis - steroids are okay for athletes' health. - True

Type II Error (False Negative) - this occurs when you fail to reject the null hypothesis when the alternative hypothesis is true
- Null hypothesis - women belong to the kitchen
- Alternative hypothesis - women do not belong to the kitchen

Write down three examples of Type I errors and type II errors scenearios stating the null hypothesis and alternative hypothesis for each

Type I Error
- Null hypothesis- covid was not engineered in a lab
- Alternative hypothesis- covid was engineered in a lab

Type II error
- Null hypothesis - Traore is not a dictator
-Alternative hypothesis - Traore is a dictator

# Correlation and Covariance
They are used to define the relationship between two different variables. They measure the strength and direction of a relationship

- Covariance - this measures how two differenet variables vary with each other. If both of the variables increase or decrease simultaneously, we say that the covariance is positive.
If one variable tends to increase while the other decreases, we say the covariance is negative.

- Correlation - is a standard measure of covariance. It is obtained by getting the covariance and dividing it by the product of the standard deviation of the two variables.


In [ ]:
import numpy as np

size_land = [0.8, 1.5, 1.9, 2.2, 3.8]
amount = [4, 5.9, 6.2, 7, 10]

print(np.cov(size_land, amount)[0][1])

2.4265


Create a python function that calculates the correlation between two parameters we pass into it. steps are as below

- Getting covariance
- Getting the standard deviation of the two varibles
- Product of the std deviations
- Covariance/ std deviation

In [ ]:
import numpy as np

def correlation(var1, var2):
  cov = np.cov(var1, var2)[0][1]
  print(f"Covariance is", np.cov(var1, var2)[0][1])
  std_var1 = np.std(var1)
  std_var2 = np.std(var2)
  print(f"Standard deviation of var1 is {std_var1}")
  print(f"Standard deviation of var2 is {std_var2}")
  corr = cov / (std_var1 * std_var2)
  return corr

var1 = [0.8, 1.5, 1.9, 2.2, 3.8]
var2 = [4, 5.9, 6.2, 890, 10]

correlation_value = correlation(var1, var2)
print(f"The correlation is: {correlation_value}")

Covariance is 37.746500000000026
Standard deviation of var1 is 0.9971960689854328
Standard deviation of var2 is 353.39536159944146
The correlation is: 0.10711129882761224


In [ ]:
import numpy as np

def get_correlation(var1,var2):
  covariance= (np.cov(var1, var2)[0][1])
  std_var1 = np.std(var1)
  std_var2 = np.std(var2)
  correlation = covariance / (std_var1 * std_var2)
  return correlation

var1 = [0.8, 1.5, 1.9, 2.2, 3.8]
var2 = [4, 5.9, 6.2, 890, 10]
correlation = get_correlation(var1, var2)
print(f"The correlation of the two is {correlation}")

The correlation of the two is 0.10711129882761224


#Linear Algebra
It is a branch of math that deals with vectors, matrices and linera transformation. It plays a crucial role in data science, particularly machine learning(model building and commpter vision)
- Vector - is an ordered collection of numbers which can represent a point in space or a set of values.It is denoted by abold letter or a lowercase letter with an arrow at the top.

- Vector addition - vectors of the same dimensions are added component wise

In [ ]:
import numpy as np

vector1 = np.array ([1, 2, 3])
scalar = 5
vector_product = vector1 * scalar
print(vector_product)

[ 5 10 15]


Scaler Multiplication-- Up Top

Multiplication - the product of the two vectors is obtained by component wise mulitiplication

In [ ]:
vector1 = np.array([3, 4, 5])
vector2 = np.array([6, 7, 8])
product = vector1 * vector2
print(product)

[18 28 40]


#Matrices
Is a rectangular array of numbers arranged in rows and columns.
A matrix is denoted by a capital letter such as A, B, C. The elements in a matrix are enclosed in square brackets or parethensis. The dimensions are denoted by the numbers or rows and columns.

In [ ]:
matrix_A = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(matrix_A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Addition - matrices of the same dimensions are added component wise

In [ ]:
matrix_B = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix_C = np.array([[12, 11, 10],
                     [9, 8, 7],
                     [6, 5, 4]])
print(matrix_B + matrix_C)

[[13 13 13]
 [13 13 13]
 [13 13 13]]


In [ ]:
print(matrix_B[0][2])

3


Create a pyhton function that does the following
1. Takes two parameters
2. Carries out matrix multiplication and return the results


In [ ]:
test_matrix_A = np.array([[13, 4],
                          [8, 8]
                          ])
test_matrix_B = np.array([[1, 19],
                          [8, 2]])

def multiplication (test_matrix_A, test_matrix_B):
  result = test_matrix_A * test_matrix_B
  return result

multiplication(test_matrix_A, test_matrix_B)

array([[13, 76],
       [64, 16]])

A=[a,b]   B=[e, f]
  [c,,d]    [g ,h]

AB =[ ae+bg af+bh]
    [ ce+dg  cf+dh]


multiplication of a 3*3 matrix

#Identity Matrix
This is a square matrix where all values in the main diagonals are 1 and all the elements are 0

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write apython  script that checks whether a matrix passed as a parameter is an identity matrix
::

In [ ]:
import numpy as np

test_matrix_B = np.array([
    [1., 19., 2],
    [8., 2., 1],
])
print(test_matrix_B.shape[1])

3


Write a python  script that checks whether a matrix passed as a parameter is an identity matrix

In [ ]:
def is_identify(matrix_A):
  rows = matrix_A.shape[0]
  columns = matrix_A.shape[1]

if rows == columns:
  identity_matrix = np.eye(rows)
  if np.array_equal(matrix_A, identity_matrix):
    print(f"{matrix_A} is an identity matrix")
return True
  pass
  else:
  print(f"{matrix_A} is NOT a square matrix, hence not an identity matrix")
  return False